###### npm install serverless@2

service: myserverlessproject2
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs20.x
  profile: nitish-serverless
  tracing:
    lambda: true
  timeout: 90
  logRetentionInDays: 30
  versionFunctions: false
  region: us-east-1


